wandb:
  enabled: true
  name: "mlp_bioresponse_baseline"
  project: "bioresponse-mlp"
  entity: "xmajercik-fiit-stu"
  run_name: "mlp_baseline_100epochs_test_tanh"
  notes: "Baseline MLP with dropout 0.3 and batch normalization"